#!/usr/bin/env bash
# Generates dist/bun-compile-entrypoint.js — the Bun compile entrypoint that
# embeds all declared assets directly into the binary.
#
# This script reads `bun.assets` glob patterns from the consumer's package.json,
# expands them, and writes a JS module that:
#   1. Imports each file with `{ type: "file" }` (tells Bun to embed it)
#   2. Sets globalThis.__EMBEDDED_ASSET_MANIFEST__ mapping logical paths → imports
#   3. Re-exports the configured entry (default: dist/bundle.js) as the main module
#
# The generated file is only consumed by `bun build --compile`. esbuild never
# sees it (esbuild doesn't support import attributes).
#
# Usage: bun-generate-manifest
#        (run from the consumer's root, after building produces the entry JS)
#
# Requires: Bun (already a hard dependency for binary compilation)

set -euo pipefail

if ! command -v bun >/dev/null 2>&1; then
  echo "ERROR: 'bun' not found on PATH. Bun is required to generate the embedded manifest." >&2
  exit 1
fi

if [ ! -f "package.json" ]; then
  echo "ERROR: No package.json found in current directory." >&2
  exit 1
fi

OUTPUT="dist/bun-compile-entrypoint.js"

OUTPUT="$OUTPUT" bun -e '
const fs = require("fs");
const path = require("path");

const cwd = process.cwd();
const outputRel = process.env.OUTPUT;
const outputAbs = path.join(cwd, outputRel);
const pkg = JSON.parse(fs.readFileSync(path.join(cwd, "package.json"), "utf8"));
const bunConfig = pkg.bun || {};
const patterns = bunConfig.assets;

if (!patterns || !Array.isArray(patterns) || patterns.length === 0) {
  if (fs.existsSync(outputAbs)) {
    fs.unlinkSync(outputAbs);
    console.log(`Removed stale ${outputRel} (no bun.assets declared)`);
  } else {
    console.log("No bun.assets patterns in package.json — skipping manifest generation");
  }
  process.exit(0);
}

// Determine what the entrypoint should re-export after setting up the manifest.
// Default is "./bundle.js" (esbuild convention); consumers can override via bun.entry.
const entry = bunConfig.entry || "./dist/bundle.js";
// Resolve relative to dist/ since the entrypoint lives there
const entryRelToOutput = path.relative(path.dirname(outputAbs), path.resolve(cwd, entry));

// Verify the entry file exists
const entryAbs = path.resolve(cwd, entry);
if (!fs.existsSync(entryAbs)) {
  console.error(`ERROR: entry file not found: ${entry}`);
  console.error(`       (resolved to ${entryAbs})`);
  console.error(`       Set "bun.entry" in package.json to your compiled entry point.`);
  process.exit(1);
}

const files = [];
for (const pattern of patterns) {
  const glob = new Bun.Glob(pattern);
  const matched = [...glob.scanSync({ cwd, onlyFiles: true, dot: false })];
  if (matched.length === 0) {
    console.error(`ERROR: asset pattern matched no files: ${pattern}`);
    console.error(`       (evaluated relative to ${cwd})`);
    process.exit(1);
  }
  files.push(...matched);
}

// Deduplicate (patterns may overlap)
const uniqueFiles = [...new Set(files)].sort();

const lines = [
  "// Auto-generated by bun-generate-manifest (@stripe/bun-toolkit) — do not edit",
  "// Bun compile entrypoint: embeds assets and re-exports the consumer entry.",
  "",
];

const importNames = [];
for (let i = 0; i < uniqueFiles.length; i++) {
  const name = `_a${i}`;
  importNames.push(name);
  // Paths are relative to dist/ (where this file lives)
  const relPath = "../" + uniqueFiles[i];
  lines.push(`import ${name} from ${JSON.stringify(relPath)} with { type: "file" };`);
}

lines.push("");
lines.push("globalThis.__EMBEDDED_ASSET_MANIFEST__ = {");
for (let i = 0; i < uniqueFiles.length; i++) {
  const comma = i < uniqueFiles.length - 1 ? "," : "";
  lines.push(`  ${JSON.stringify(uniqueFiles[i])}: ${importNames[i]}${comma}`);
}
lines.push("};");
lines.push("");
lines.push(`await import(${JSON.stringify("./" + entryRelToOutput)});`);
lines.push("");

fs.mkdirSync(path.dirname(outputAbs), { recursive: true });
fs.writeFileSync(outputAbs, lines.join("\n"));
console.log(`Generated ${outputRel} (${uniqueFiles.length} embedded assets from ${patterns.length} pattern(s))`);
console.log(`  Entry: ${entry} (resolved as ./${entryRelToOutput} from dist/)`);
'
